# Generated by Django 4.2 on 2023-04-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0004_rename_property_task_proyect'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proyect',
            new_name='Project',
        ),
    ]
